#!/usr/bin/env bash

export HOST_IPV4
export REPLACE_OS_VARS=true

# or read it from terraform
HOST_IPV4=$(
  ifconfig \
    | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' \
    | grep -vE '^10\.' # not interested in private network
)
